services:
  novelgenerator:
    image: novelgenerator
    build:
      context: novel-generator
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
